project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Restaurants in NYC"
  author:
    - Federico Giorgi(fg2617)
    - Rencong Jiang(rj2798)
  repo-url: https://github.com/fede-giorgi/restaurants-in-nyc
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


